### ISSUE TITLE
Run this examples 

### ISSUE THREAD

**Issue by elile** [missioncommand/emp3-android-examples#26]
Hi, How can I run this example?
All I get is "Could not get unknown property 'empUsername'..."
Thanks

**Comment by michael-spinelli** [comment]
We're working on removing the dependency this is related to. @rsupnekar , is there any way this can be run with a DI2E account?

**Comment by michael-spinelli** [comment]
@elile, Try it now.  We removed the need for those properties.

**Comment by elile** [comment]
Still getting:
Error:(25, 0) Could not get unknown property 'empUsername' for object of type org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension.

**Comment by elile** [comment]
This removal is with the branch "emp3-android-examples--24-test-issue-232" ?
If yes now I get:
Error:Could not get unknown property 'empUsername' for Credentials [username: null] of type org.gradle.api.internal.artifacts.repositories.DefaultPasswordCredentials_Decorated.

**Comment by rsupnekar** [comment]
That branch is not merged yet.  It is still work in progress.  However, if you want to use the cmapi.jar checked into this branch, you are welcome to use it.  You can then modify the gradle file to build the example you want with a local copy of cmapi.jar.
