### ISSUE TITLE
#6 Update geojson example for changes in sdk

### ISSUE THREAD

**Issue by rsupnekar** [missioncommand/emp3-android-examples#6]
The example is out of sync with changes made to the cmapi example geojson data file.

**Comment by mubinakhan** [comment]
![screenshot_20170210-140149 1](https://cloud.githubusercontent.com/assets/25485443/22839974/af2cadb4-ef99-11e6-9b83-5555fdcc1703.png)

**Comment by rsupnekar** [comment]
The line sent you goes into the gradle.properties that I opened.  It is under Users\mubina.khan\.gradle.

So your gradle.properties contents would like lie this:


empUsername=.... (your name)
empPassword=.... (your password)
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx1536M

________________________________

**Comment by mubinakhan** [comment]
Done..

-----Original Message-----
